name: Access HerokuApp
on:
  repository_dispatch:
    types:
      - proxy
  schedule:
    #     - cron: '24 0,6,12 * * *'
    - cron: "24 0,2,4,6,8,10,12,14 * * *"

jobs:
  lfproxz:
    runs-on: ubuntu-latest
    steps:
      - name: Access lfproxz
        run: curl ${{ secrets.PROXYURL }}
